target:
	g++ 1/segitiga_mantap.cpp shared/shader.cpp -o segitiga_mantap_1 -lGL -lGLEW -lglfw
	g++ 2/segitiga_mantap.cpp shared/shader.cpp -o segitiga_mantap_2 -lGL -lGLEW -lglfw
	g++ 3/segitiga_mantap.cpp shared/shader.cpp -o segitiga_mantap_3 -lGL -lGLEW -lglfw

run:
	echo "Command to run program : make run[1|2|3]"

run1:
	./segitiga_mantap_1

run2:
	./segitiga_mantap_2

run3:
	./segitiga_mantap_3
